### ISSUE TITLE
Select a team

### ISSUE THREAD

**Issue by jeremykraemer** [tbmc/sporteasy-calendar-connector#1]
Hello,

Is it possible to add the possibility of specifying a team in addition to the username/password? 

- By default, if nothing is specified, we return all the user's events (multiple teams), as they currently work
- If an ID or a team name (to be chosen) is specified, only the events of this team are returned

This would make it possible to create several calendars when you belong to several teams. 

```
{
    "username": "...",
    "password": "...",
    "team": "..."
}
```

**Comment by tbmc** [comment]
Hello,

I hope it works for you.
Do not hesitate if you have any problem with it.

**Comment by jeremykraemer** [comment]
It works perfectly, thank you !
